version: '3'
services:
  aws-smtp-relay:
    image: loopingz/aws-smtp-relay
    ports:
      - 10025:10025
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  hapi-fhir:
    image: registry.ruvos.com/ersd/ersd-hapi-fhir
    ports:
      - 8081:8080
    environment:
      DATASOURCE_USERNAME: hapi_user
      DATASOURCE_PASSWORD: S3cretP8ss
      DATASOURCE_DRIVER: org.h2.Driver
      DATASOURCE_URL: jdbc:h2:file:/var/lib/jetty/target/database/h2
      HIBERNATE_DIALECT: org.hibernate.dialect.H2Dialect
    volumes:
      - hapi-fhir-data:/var/lib/jetty/target
    depends_on:
      - aws-smtp-relay
  keycloak:
    image: jboss/keycloak:7.0.0
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/jboss/keycloak/
    depends_on:
      - aws-smtp-relay
  web:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./dist/apps:/ersd
      - ./node_modules:/ersd/server/node_modules
    depends_on:
      - hapi-fhir
      - keycloak
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
volumes:
  hapi-fhir-data:
  keycloak-data:
