version: '3'
services:
  aws-smtp-relay:
    image: loopingz/aws-smtp-relay
    ports:
      - 10025:10025
  hapi-fhir:
    image: registry.ruvos.com/ersd/ersd-hapi-fhir
    ports:
      - 8081:8080
    environment:
      DATASOURCE_DRIVER: 'org.apache.derby.jdbc.EmbeddedDriver'
      DATASOURCE_URL: 'jdbc:derby:directory:target/jpaserver_derby_files;create=true'
      HIBERNATE_DIALECT: 'ca.uhn.fhir.jpa.util.DerbyTenSevenHapiFhirDialect'
  keycloak:
    image: jboss/keycloak:7.0.0
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  web:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./dist/apps:/ersd
      - ./node_modules:/ersd/server/node_modules