services:
  ersd-hapi-fhir:
    image: hapiproject/hapi:v6.8.0
    ports:
      - 8081:8080
    environment:
      spring.datasource.url: jdbc:postgresql://hapi-db:5432/hapi_db
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.datasource.username: myuser
      spring.datasource.password: secret
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hapi.fhir.fhir_version: R4
      hapi.fhir.client_id_strategy: ANY
    depends_on:
      - hapi-db
  hapi-db:
    image: postgres:9.4.26-alpine
    volumes:
      - hapi-fhir-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hapi_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: '--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start --metrics-enabled=true'
    ports:
      - 8085:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_HEALTH_ENABLED: true
      KC_DB_URL_HOST: postgres
      KC_DB_SCHEMA: public
      KC_DB_NAME: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
    depends_on:
      - postgres
  web:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./dist/apps:/ersd
      - ./node_modules:/ersd/server/node_modules
    depends_on:
      - ersd-hapi-fhir
      - keycloak
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
volumes:
  hapi-fhir-data:
  postgres_data:
