version: '3'
services:
  hapi-fhir:
    image: registry.ruvos.com/ersd/ersd-hapi-fhir
    build:
      context: ./apps/hapi-fhir
    ports:
      - 8081:8080
    environment:
      DATASOURCE_USERNAME: hapi_user
      DATASOURCE_PASSWORD: S3cretP8ss
      DATASOURCE_DRIVER: org.h2.Driver
      DATASOURCE_URL: jdbc:h2:file:/var/lib/jetty/target/database/h2
      HIBERNATE_DIALECT: org.hibernate.dialect.H2Dialect
      SERVER_ADDRESS: http://hapi-fhir:8080/hapi-fhir-jpaserver/fhir
      EMAIL_FROM: ${ERSD_EMAIL_FROM}
      EMAIL_HOST: ${ERSD_EMAIL_HOST}
      EMAIL_PORT: ${ERSD_EMAIL_PORT}
      EMAIL_USERNAME: ${ERSD_EMAIL_USERNAME}
      EMAIL_PASSWORD: ${ERSD_EMAIL_PASSWORD}
    volumes:
      - hapi-fhir-data:/var/lib/jetty/target
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: '--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start'
    ports:
      - 8085:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_SCHEMA: public
      KC_DB_NAME: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
    depends_on:
      - postgres
  web:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./dist/apps:/ersd
      - ./node_modules:/ersd/server/node_modules
    depends_on:
      - hapi-fhir
      - keycloak
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
volumes:
  hapi-fhir-data:
  postgres_data:
